INSERT INTO organizations ("name", "description", "street_number", "street_name", "unit", "city", "province", "country", "postal_code", "email", "password", "phone", "category", "website")
VALUES
    ('Children Care Foundation', 'Providing shelter and education to underprivileged children.', '123', 'Sunset Boulevard', 'Floor 2', 'Metropolis', 'Metro Province', 'Charityland', '12345', 'info@children-care.org', 'password', '+1234567890', 'Children Welfare', 'https://children-care.org'),
    ('Elderly Support Network', 'Offering companionship and aid to the elderly community.', '456', 'Maple Avenue', NULL, 'Villageville', 'Aged State', 'Helping Hands Country', '67890', 'contact@elderly-support.net', 'password', '+9876543210', 'Elderly Assistance', 'https://elderly-support.net'),
    ('Animal Haven Sanctuary', 'Rescuing and rehabilitating abused and abandoned animals.', '789', 'Paws Street', 'Suite 101', 'Petropolis', 'Animal State', 'Furville', '54321', 'rescue@animal-haven.org', 'password', '+5555555555', 'Animal Welfare', 'https://animal-haven.org'),
    ('Green Earth Alliance', 'Promoting environmental conservation and sustainable practices.', '111', 'Greenway Road', NULL, 'Greentown', 'Eco Province', 'EcoNation', '98765', 'info@green-earth-alliance.org', 'password', '+1112223333', 'Environmental Sustainability', 'https://green-earth-alliance.org'),
    ('Healthcare Without Borders', 'Delivering medical aid and healthcare services globally.', '222', 'Healthcare Plaza', 'Building C', 'Medicity', 'Health State', 'GlobalCare', '54321', 'care@healthcare-without-borders.org', 'password', '+2223334444', 'Healthcare Support', 'https://healthcare-without-borders.org'),
    ('Education Empowerment Foundation', 'Empowering individuals through accessible education initiatives.', '333', 'Knowledge Lane', 'Floor 5', 'Eduville', 'Edu State', 'LearnNation', '13579', 'info@education-empowerment.org', 'password', '+3334445555', 'Education Access', 'https://education-empowerment.org'),
    ('Food Bank Coalition', 'Distributing food resources to combat hunger in local communities.', '444', 'Harvest Street', NULL, 'Foodville', 'Aid Province', 'NourishNation', '24680', 'support@foodbank-coalition.org', 'password', '+4445556666', 'Food Aid', 'https://foodbank-coalition.org'),
    ('Artistic Expression Center', 'Fostering creativity and arts education for disadvantaged youth.', '555', 'Artistry Avenue', 'Suite 1', 'Artropolis', 'Creative State', 'ArtNation', '97531', 'info@artistic-expression.org', 'password', '+5556667777', 'Art & Culture', 'https://artistic-expression.org'),
    ('Community Builders Coalition', 'Empowering communities through infrastructure and support programs.', '666', 'Unity Road', NULL, 'Communityville', 'Support State', 'BuildNation', '86420', 'support@community-builders.org', 'password', '+6667778888', 'Community Development', 'https://community-builders.org'),
    ('Disability Inclusion Initiative', 'Advocating for accessibility and inclusion for people with disabilities.', '777', 'Access Lane', 'Suite 10', 'Inclusion City', 'Accessible State', 'IncludeNation', '73204', 'info@disability-inclusion.org', 'password', '+7778889999', 'Disability Rights', 'https://disability-inclusion.org');
