INSERT INTO projects ("org_id", "name", "start_date", "end_date", "status", "description", "project_type", "published")
VALUES
    (1, 'Education Scholarships 2023', '2023-01-15', '2023-12-31', 'Active', 'The "Education Scholarships 2023" project aims to provide comprehensive educational scholarships to disadvantaged children from low-income backgrounds. The initiative encompasses covering tuition fees, purchasing books, school supplies, and uniforms, offering mentorship programs, and facilitating extracurricular activities. By addressing financial barriers, this project seeks to enhance educational access and opportunities for a brighter future.', 'Education Assistance', true),
    (2, 'Elderly Companionship Drive', '2023-02-01', '2023-08-31', 'Active', 'The "Elderly Companionship Drive" project endeavors to create sustainable programs offering companionship and support to the elderly population. Through regular visits, social events, engaging activities, and emotional support, the initiative aims to combat social isolation and improve the overall well-being of senior citizens. Volunteers provide companionship and assist with daily tasks, fostering a sense of community and care.', 'Elderly Support', true),
    (3, 'Animal Rescue & Rehabilitation', '2023-03-01', '2023-10-31', 'Active', 'The "Animal Rescue & Rehabilitation" project focuses on rescuing, providing medical care, and rehabilitating animals in distress. The initiative collaborates with veterinary experts and shelters to ensure the well-being of rescued animals. Alongside rescue efforts, the project aims to promote awareness about animal welfare, advocate for ethical treatment, and find suitable homes for animals in need.', 'Animal Welfare', true),
    (4, 'Green Earth Awareness Campaign', '2023-04-01', '2023-11-30', 'Active', 'The "Green Earth Awareness Campaign" is dedicated to raising awareness about environmental conservation and fostering sustainable practices. Through educational campaigns, tree planting initiatives, waste management programs, and community engagement, the project aims to inspire individuals to adopt eco-friendly habits and contribute to the preservation of our planet for future generations.', 'Environmental Awareness', true),
    (5, 'Global Healthcare Initiative', '2023-05-01', '2023-12-31', 'Active', 'The "Global Healthcare Initiative" endeavors to provide vital healthcare aid to underserved regions worldwide. The project involves establishing medical facilities, sending medical teams, and delivering essential medicines and healthcare services to improve health outcomes in regions facing healthcare disparities. By addressing healthcare gaps, the initiative aims to promote health equity and well-being for vulnerable populations.', 'Healthcare Support', true),
    (6, 'Youth Education Workshops', '2023-06-01', '2023-09-30', 'Active', 'The "Youth Education Workshops" project focuses on empowering young individuals through skill-building workshops, career guidance sessions, and leadership development programs. The initiative aims to equip youth with essential skills, knowledge, and confidence to navigate educational and career pathways successfully. Through interactive sessions and mentorship, the project aims to inspire and enable the next generation.', 'Youth Development', true),
    (7, 'Community Food Drive', '2023-07-01', '2023-11-30', 'Active', 'The "Community Food Drive" project addresses food insecurity by collecting and distributing food to needy families and individuals. Collaborating with local organizations and volunteers, the project organizes food drives, establishes community kitchens, and implements nutritional programs to ensure access to adequate and healthy food for those facing hunger. The goal is to foster food security and alleviate hunger in the community.', 'Food Aid', true),
    (8, 'Artistic Expression Camps', '2023-08-01', '2023-10-31', 'Active', 'The "Artistic Expression Camps" project is designed to offer creative arts camps for underprivileged youth. Through immersive art experiences, mentorship from artists, and exposure to various art forms, the initiative aims to unlock the creative potential of young individuals. By providing a platform for artistic expression, the project encourages self-discovery, boosts self-esteem, and nurtures artistic talents.', 'Arts & Culture', true),
    (9, 'Infrastructure Enhancement Project', '2023-09-01', '2023-12-31', 'Active', 'The "Infrastructure Enhancement Project" seeks to improve infrastructure in underserved communities by upgrading roads, constructing community centers, and enhancing access to basic amenities. The project aims to create a sustainable impact by addressing infrastructure gaps and enhancing the overall living conditions in marginalized areas.', 'Community Development', true),
    (10, 'Disability Awareness Campaign', '2023-10-01', '2023-11-30', 'Active', 'The "Disability Awareness Campaign" is dedicated to promoting awareness about disability inclusion and advocating for equal rights. Through educational campaigns, workshops, and initiatives, the project aims to challenge stereotypes, foster inclusivity, and create a more accessible and accommodating environment for individuals with disabilities.', 'Disability Rights Advocacy', true),
    (1, 'Education Scholarships 2022', '2022-01-15', '2022-12-31', 'Inactive', 'The "Education Scholarships 2022" project aimed to provide educational scholarships to disadvantaged children, covering tuition fees, books, and school supplies, and offering mentorship programs. While the project is currently inactive, it had a significant impact by supporting educational access for children from low-income backgrounds.', 'Education Assistance', true);
