INSERT INTO items ("project_id", "item_description", "quantity_needed", "urgent", "status", "item_price")
VALUES
    (1, 'School Supplies', 500, true, 'Active', NULL),
    (2, 'Elderly Care Packages', 200, false, 'Approved', 20.00),
    (3, 'TLC Adult Dog Food', 50, true, 'Active', 72.95),
    (4, 'Environmental Awareness Flyers', 1000, false, 'Approved', 0.50),
    (5, 'Medical Supply Kits for Aid Missions', 100, true, 'Active', 50.00),
    (6, 'Books for Education Workshops', 200, false, 'Approved', NULL),
    (7, 'Non-perishable Food Items', 600, true, 'Active', NULL),
    (8, 'Art Supply Kits for Creative Workshops', 100, false, 'Approved', 60.00),
    (9, 'Construction Material Bundles for Infrastructure', 120, true, 'Active', 200.00),
    (10, 'Wheelchairs', 3, true, 'Approved', 2500.00),
    (11, 'School Supply Kits', 150, false, 'Active', 25.95),
    (1, 'Textbooks for Scholarship Recipients', 200, false, 'Active', 99.99),
    (1, 'Laptops for Educational Support', 150, false, 'Active', 799.99),
    (2, 'Companion Care Kits for Seniors', 100, false, 'Active', 20.00),
    (3, 'Medical Supply Kits for Animal Care', 120, true, 'Active', 40.00),
    (4, 'Recycled Paper for Campaign Flyers', 500, false, 'Active', 0.60),
    (5, 'Essential Medications for Healthcare Missions', 80, true, 'Active', 30.00),
    (6, 'Storybooks for Youth Workshops', 50, false, 'Active', NULL),
    (7, 'Canned Food', 400, false, 'Active', NULL),
    (8, 'Paints and Canvases for Artistic Camps', 80, false, 'Active', 65.00),
    (9, 'Building Material Kits for Community Projects', 30, false, 'Active', 320.00),
    (10, 'Accessibility Devices for Awareness Campaign', 15, false, 'Active', NULL),
    (2, 'Social Activity Supplies for Seniors', 80, false, 'Active', 12.50),
    (5, 'First Aid Kits for Healthcare Missions', 50, true, 'Active', 24.00),
    (6, 'Educational Games for Youth Workshops', 30, false, 'Active', NULL),
    (8, 'Sketchpads for Artistic Camps', 120, false, 'Active', 3.33),
    (9, 'Tools for Community Projects', 30, false, 'Active', 26.00),
    (10, 'Braille Books for Awareness Campaign', 30, false, 'Active', 66.67),
    (1, 'bookmarks', 2850, true, 'Active', NULL),
    (5, 'spongebob bandaids', 5000, false, 'Active', NULL),
    (7, 'cans of beans', 600, true, 'Active', NULL);
